# Generated by Django 4.1.1 on 2023-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_youtube_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todoId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
