# Generated by Django 4.1.1 on 2023-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_homework_homeworkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
