# Generated by Django 4.1.1 on 2023-05-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_todo_date_todo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todoId',
        ),
    ]
